export default {

    CURRENT_LOCATION_CHANGED: "CURRENT_LOCATION_CHANGED",
    POST_CREATED: "POST_CREATED",
    POSTS_RECEIVED: "POSTS_RECEIVED",
    CURRENT_USER_RECEIVED: "CURRENT_USER_RECEIVED"


}
